### ISSUE TITLE
Restrict PR hooks to open/edit events

### ISSUE THREAD

**Issue by surli** [monperrus/gakoci#2]
It seems that PR hooks are launched for every kind of events on PR (see https://developer.github.com/v3/activity/events/types/#pullrequestevent). IMHO it's useless to launch hooks for closed PR event for example, or even for label-related event.

Then wdyt about restricting the launch of hooks on opening/editing PR?

**Comment by monperrus** [comment]
I'd say it would overload the command-line. Hooks can access this info through the payload.
